# Generated by Django 5.0.7 on 2024-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_spending'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='duration',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=2),
        ),
    ]
